version: '2.3'

x-project:
  &project ckanext-data-qld-theme

x-volumes:
  &default-volumes
  volumes:
    - /srv/app/src/app ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    - ./ckanext:/srv/app/src/app/ckanext:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    - ./test:/srv/app/src/app/test:${VOLUME_FLAGS:-delegated} ### Local overrides to mount host filesystem. Automatically removed in CI and PROD.
    ##- /app/filestore # Override for environment without host mounts. Automatically uncommented in CI.

x-environment:
  &default-environment
  AMAZEEIO: AMAZEEIO
  no_proxy: "ckan,postgres,postgres-datastore,redis,solr,chrome,mailhog.docker.amazee.io"

x-user:
  &default-user
  # The default user under which the containers should run.
  # Change this if you are on linux and run with another user than id `1000`.
  user: '1000'

services:

  ckan:
    build:
      context: .
      dockerfile: .docker/Dockerfile.ckan
    depends_on:
      - postgres
      - solr
    networks:
      - default
    ports:
      - "3000"
    image: *project
    <<: *default-volumes
    environment:
      <<: *default-environment

  postgres:
    image: ckan/ckan-postgres-dev:2.8
    ports:
      - "5432"
    networks:
      - default
    <<: *default-user
    environment:
      <<: *default-environment

  postgres-datastore:
    image: ckan/ckan-postgres-dev:2.8
    ports:
      - "5432"
    <<: *default-user
    networks:
      - default
    environment:
      <<: *default-environment

  redis:
    image: redis:3
    <<: *default-user
    environment:
      <<: *default-environment
    networks:
      - default

  solr:
    image: ckan/ckan-solr-dev:2.8
    user: '8983'
    ports:
      - "8983"
    environment:
      <<: *default-environment
    networks:
      - default

  chrome:
    image: selenium/standalone-chrome:3.141.59-oxygen
    shm_size: '1gb'
    depends_on:
      - ckan
    <<: *default-volumes
    <<: *default-user
    environment:
      <<: *default-environment
    networks:
      - default

volumes:
  solr-data: {}
