---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test:
    strategy:
      matrix:
        application: [OpenData]
        ckan-version: ['2.8']
        target_environment: [DEV]
      fail-fast: false

    name: ${{ matrix.application }} ${{ matrix.target_environment }} infrastructure build
    runs-on: ubuntu-latest
    container: openknowledge/ckan-dev:2.8
    services:
      solr:
        image: ckan/ckan-solr-dev:${{ matrix.ckan-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
      chrome:
        image: selenium/standalone-chrome:3.141.59-oxygen
        options:
          --shm-size 1g

    timeout-minutes: 30
    env:
      VARS_TYPE: ${{ matrix.application }}
      DEPLOY_ENV: ${{ matrix.target_environment }}

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          python setup.py develop

      - name: Lint
        run: flake8 ckanext

      - name: Initialise database
        run: |
          CKAN_USER_NAME="${CKAN_USER_NAME:-admin}"
          CKAN_USER_PASSWORD="${CKAN_USER_PASSWORD:-Password123!}"
          CKAN_USER_EMAIL="${CKAN_USER_EMAIL:-admin@localhost}"
          CKAN_INI="${CKAN_INI:-/srv/app/production.ini}"
          CKAN_SITE_URL="${CKAN_SITE_URL:-http://localhost:5000}"
          cp .docker/test-github.ini $CKAN_INI
          paster --plugin=ckan db clean -c $CKAN_INI
          paster --plugin=ckan db init -c $CKAN_INI
          paster --plugin=ckan user add "${CKAN_USER_NAME}" email="${CKAN_USER_EMAIL}" password="${CKAN_USER_PASSWORD}" -c $CKAN_INI
          paster --plugin=ckan sysadmin add "${CKAN_USER_NAME}" -c $CKAN_INI
          CKAN_ACTION_URL="${CKAN_SITE_URL}/api/action"
          API_KEY=$(paster --plugin=ckan user $CKAN_USER_NAME -c ${CKAN_INI} | tr -d '\n' | sed -r 's/^(.*)apikey=(\S*)(.*)/\2/')
          paster --plugin=ckan create-test-data hierarchy -c ${CKAN_INI}
          paster --plugin=ckan create-test-data -c ${CKAN_INI}

      - name: Run unit tests
        timeout-minutes: 15
        run: nosetests

      - name: Run integration tests
        run: |
          . .env
          behave test/features || [ "${ALLOW_BDD_FAIL:-0}" -eq 1 ]
        timeout-minutes: 15
