---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false

    name: Continuous Integration build
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 5

      - name: Build
        run: .circleci/build.sh
        timeout-minutes: 15

      - name: Test
        run: .circleci/test.sh
        timeout-minutes: 20

      - name: Retrieve screenshots
        if: failure()
        run: .circleci/process-artifacts.sh
        timeout-minutes: 3

      - name: Upload screenshots
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: screenshots
          path: /tmp/artifacts/behave/screenshots
        timeout-minutes: 3
