---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:

jobs:
  test:
    strategy:
      fail-fast: false

    name: OpenData theme build
    runs-on: ubuntu-latest
    container: integratedexperts/ci-builder

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Start containers
        run: docker-compose up

      - name: Create test data
        run: docker exec $(docker-compose ps -q ckan) /srv/app/src/app/scripts/init.sh

      - name: Lint
        run: docker exec $(docker-compose ps -q ckan) sh -c "flake8 ckanext"

      - name: Run unit tests
        timeout-minutes: 15
        run: docker exec $(docker-compose ps -q ckan) nosetests

      - name: Run integration tests
        run: docker exec $(docker-compose ps -q ckan) sh -c "behave test/features" || [ "${ALLOW_BDD_FAIL:-0}" -eq 1 ]
        timeout-minutes: 15
