---
#based on https://raw.githubusercontent.com/ckan/ckanext-scheming/master/.github/workflows/test.yml
# alternative https://github.com/ckan/ckan/blob/master/contrib/cookiecutter/ckan_extension/%7B%7Bcookiecutter.project%7D%7D/.github/workflows/test.yml
name: Tests
on:
  push:
  schedule:
    - cron: "0 0 1 * *"

jobs:
  test:
    strategy:
      matrix:
        application: [OpenData]
        ckan-version: ['2.8']
        target_environment: [DEV]
      fail-fast: false

    name: ${{ matrix.application }} ${{ matrix.target_environment }} infrastructure build
    runs-on: ubuntu-latest
    services:
      solr:
        image: ckan/ckan-solr-dev:${{ matrix.ckan-version }}
      postgres:
        image: ckan/ckan-postgres-dev:${{ matrix.ckan-version }}
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3

    timeout-minutes: 30
    env:
      VARS_TYPE: ${{ matrix.application }}
      DEPLOY_ENV: ${{ matrix.target_environment }}

    steps:
      - uses: actions/setup-python@v2
        with:
          python-version: '2.7'

      - uses: actions/checkout@v2
        timeout-minutes: 2

      - name: Install tools
        timeout-minutes: 3
        run: |
          # if sudo doesn't exist, assume we're root and don't need it
          SUDO=$(which sudo || true)
          $SUDO apt-get update
          which docker-compose > /dev/null || \
            ($SUDO apt-get install -y docker-compose)
          which ahoy > /dev/null || \
            ($SUDO wget -q https://github.com/devinci-code/ahoy/releases/download/1.1.0/ahoy-`uname -s`-amd64 -O /usr/local/bin/ahoy \
              && $SUDO chmod +x /usr/local/bin/ahoy)
          which composer > /dev/null || \
            ($SUDO apt-get install -y php && wget -O composer-setup.php https://getcomposer.org/installer && $SUDO php composer-setup.php)
          which pygmy > /dev/null || \
            ($SUDO apt-get install -y ruby && $SUDO gem install pygmy)
          $SUDO pip install -r requirements-dev.txt

      - name: Lint
        run: flake8 ckanext

      - name: Run unit tests
        timeout-minutes: 15
        run: nosetests

      - name: Run integration tests
        uses: ./.github/actions/bdd
        timeout-minutes: 15
